import sys
import argparse
from pathlib import Path

from .headlessXttsTrain2 import run_tts_headless, load_model_headless

# Global variable for the loaded model (needed for inference step)
XTTS_MODEL = None

def parse_args(args=None):
    parser = argparse.ArgumentParser(description="Headless XTTS Fine-tuning and Inference Script")

    # General Arguments
    parser.add_argument("--lang", type=str, default="en", help="Language of the dataset (ISO 639-1 code, e.g., en, es, fr).", choices=["en","es","fr","de","it","pt","pl","tr","ru","nl","cs","ar","zh","hu","ko","ja"])
    parser.add_argument("--input_text", type=str, default="This is a sentence generated by model.", help="Text to use for generating the output WAV.")
    parser.add_argument("--model_dir", type=str, default="", help="Path to directory containing model.pth, config.json, vocab.json and speakers_xtts.pth files of fine-tuned model.")
    parser.add_argument("--reference_audio", type=str, default="/absolute/path/output.wav", help="Path to reference audio sample of the target voice. Even fine-tuned xtts needs it.")
    parser.add_argument("--output_audio", type=str, default="./output.wav", help="Path to the output generated file.")

    # Inference Arguments
    parser.add_argument("--temperature", type=float, default=0.75, help="TTS inference temperature.")
    parser.add_argument("--length_penalty", type=float, default=1.0, help="TTS inference length penalty.")
    parser.add_argument("--repetition_penalty", type=float, default=5.0, help="TTS inference repetition penalty.")
    parser.add_argument("--top_k", type=int, default=50, help="TTS inference top K.")
    parser.add_argument("--top_p", type=float, default=0.85, help="TTS inference top P.")
    parser.add_argument("--no_sentence_split", action="store_true", help="Disable sentence splitting during TTS inference.")

    return parser.parse_args(args)

def run_inference(args):
    # --- Setup Paths ---
    output_audio_path = Path(args.output_audio).resolve()
    reference_audio_path = Path(args.reference_audio).resolve()
    model_dir = Path(args.model_dir).resolve()

    # --- Load Model ---
    status = load_model_headless(
        xtts_checkpoint=str(model_dir / "model.pth"),
        xtts_config=str(model_dir / "config.json"),
        xtts_vocab=str(model_dir / "vocab.json"),
        xtts_speaker=str(model_dir / "speakers_xtts.pth")
    )
    if "failed" in status.lower() or "error" in status.lower():
        print(f"Error loading trained model: {status}")
        sys.exit(1)

    # --- Inference ---
    status, generated_wav = run_tts_headless(
        lang=args.lang,
        tts_text=args.input_text,
        speaker_audio_file=str(reference_audio_path), # Pass absolute path to reference
        output_wav_path=str(output_audio_path), # Pass absolute path for output
        temperature=args.temperature,
        length_penalty=args.length_penalty,
        repetition_penalty=args.repetition_penalty,
        top_k=args.top_k,
        top_p=args.top_p,
        sentence_split=not args.no_sentence_split
    )
    if "failed" in status.lower() or "error" in status.lower():
        print(f"Error generating example TTS: {status}")
        sys.exit(1)

def run_from_api(params_dict):
    # Convert the params_dict to command-line style arguments
    cmd_args = []
    for key, value in params_dict.items():
        if isinstance(value, bool):
            # Handle boolean flags
            if value:
                cmd_args.append(f"--{key}")
        else:
            # Handle regular arguments with values
            cmd_args.append(f"--{key}")
            cmd_args.append(str(value))

    # Parse these arguments with the same parser
    args = parse_args(cmd_args)
    return run_inference(args)

def main():
    args = parse_args()
    return run_inference(args)


if __name__ == "__main__":
    main()
